export type PredefinedColor = keyof typeof Color;

export const Color = {
  blueDark: "var(--blue-dark)",
  blueDark70: "var(--blue-dark-70)",
  blueDark30: "var(--blue-dark-30)",
  blueDark15: "rgb(2 2 30 / .15)",
  blue: "var(--blue)",
  greyDark: "var(--grey-dark)",
  greyLight: "var(--grey-light)",
  yellow: "var(--yellow)",
  white: "var(--white)",
  white70: "var(--white-70)",
  white30: "var(--white-30)",
  white20: "var(--white-20)",
  blueLight: "var(--blue-light)",
  tomato: "var(--tomato)",
  purple: "var(--purple)",
  greyMedium: "var(--grey-medium)",
  red: "var(--red)",
  blueLink: "var(--blue-link)",
  transparent: "var(--transparent)",
  coolGray: "rgb(168 168 209)",
  coolGray20: "rgb(168 168 209 / .2)",
  homeBlue: "rgb(56 39 199)",
  homeBlue17: "rgb(56 39 199 / .17)",
  green: "rgb(69, 183, 99)",
  antiFlashWhite: "rgb(234, 234, 236)",
} as const;
